### ISSUE TITLE
acompletion 的stream模式，没有finish_reason字段

### ISSUE THREAD

**Issue by LanceLuoyuan** [boyueluzhipeng/GPT_CodeInterpreter#20]
function_ui_message None
2023-09-04 17:55:41 - 'finish_reason'
Traceback (most recent call last):
  File "/Users/luoyuan/opt/anaconda3/envs/py39_codeinterpreter_web/lib/python3.9/site-packages/chainlit/utils.py", line 36, in wrapper
    return await user_function(**params_values)
  File "app.py", line 363, in run_conversation
    await on_message(user_message)
  File "app.py", line 173, in on_message
    if stream_resp.get('choices', [])[0]["finish_reason"] == "stop":
KeyError: 'finish_reason'

请教下作者有碰到这个问题吗

**Comment by boyueluzhipeng** [comment]
你用的是官方的api吗？如果是一些别人开放的，可能存在这个问题

**Comment by LanceLuoyuan** [comment]
是官方的，我用的环境变量是这个

OPENAI_API_KEY=****
OPENAI_API_BASE=https://api.openai.com/v1/
OPENAI_MODEL=gpt-4
MAX_TOKENS=5000
LANGUAGE=chinese

在官方的社区里也看到了这个问题 https://community.openai.com/t/completion-finish-reason-is-missing-when-stream-true/90526
