### ISSUE TITLE
BUG：An error must be reported when executing Python scripts

### ISSUE THREAD

**Issue by linghongli** [boyueluzhipeng/GPT_CodeInterpreter#4]
![11](https://github.com/boyueluzhipeng/GPT_CodeInterpreter/assets/2770205/538ce853-2718-4896-bc70-1377c1978e51)
![22](https://github.com/boyueluzhipeng/GPT_CodeInterpreter/assets/2770205/9b4e815d-c45b-4f1f-809b-81c5c3069d5c)

**Comment by boyueluzhipeng** [comment]
你需要查看下，你现在的版本是最新的吗？新版本的我改过了函数名称，由python改成了python_exec,然后这一块，想问下你用的是3.5模型吗？如果是的话，确实可能会出现这种问题

**Comment by boyueluzhipeng** [comment]
还有一个可以减少这问题的方案，就是在初始化openai的时候，app.py 处 @cl.on_chat_start 下面的函数中，将content修改成一些特定的说明，例如要求它"必须严格按照函数传参说明进行函数调用"，设定角色，"他是一个很好的python开发者"

> ![11](https://user-images.githubusercontent.com/2770205/254773835-538ce853-2718-4896-bc70-1377c1978e51.png) ![22](https://user-images.githubusercontent.com/2770205/254773845-9b4e815d-c45b-4f1f-809b-81c5c3069d5c.png)

**Comment by linghongli** [comment]
您好，是3.5模型

**Comment by linghongli** [comment]
非常感谢您的回复，请问能修改成兼容3.5模型吗？因为现在能有4模型api权限还是很少的

**Comment by linghongli** [comment]
报错的是这个位置，返回python脚本数据时，arguments参数数据格式并不是json的
![image](https://github.com/boyueluzhipeng/GPT_CodeInterpreter/assets/2770205/2e33d05f-4bae-4dc5-85b5-e42caa70839d)

![image](https://github.com/boyueluzhipeng/GPT_CodeInterpreter/assets/2770205/353c7432-9387-45bc-8848-07d9754c5fe6)

**Comment by linghongli** [comment]
> cl.on_chat_start

不是prompt的问题，是代码本身的数据处理bug哈

**Comment by linghongli** [comment]
2023-07-20 16:22:49 - invalid syntax (<unknown>, line 1)
Traceback (most recent call last):
  File "app.py", line 154, in on_message
    arguments = json.loads(openai_message.get("function_call").get("arguments"))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/danqing/IdeaProjects/test/venv/lib/python3.8/site-packages/chainlit/utils.py", line 36, in wrapper
    return await user_function(**params_values)
  File "app.py", line 232, in run_conversation
    await on_message(user_message)
  File "app.py", line 157, in on_message
    arguments = ast.literal_eval(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    import os
    ^
SyntaxError: invalid syntax

**Comment by linghongli** [comment]
求解答，请问能加vx沟通不tom_ling
